// This file was generated by RedwoodJS
import type { Scenario, DefineScenario } from '@redwoodjs/testing/api'

declare global {
  /**
   * Note that the scenario name must match the exports in your {model}.scenarios.ts file
   */
  const scenario: Scenario
  const defineScenario: DefineScenario
}
