// This file was generated by RedwoodJS
import BarPageType from '/Users/tobbe/dev/redwood/redwood/__fixtures__/example-todo-main/web/src/pages/BarPage/BarPage'
import FatalErrorPageType from '/Users/tobbe/dev/redwood/redwood/__fixtures__/example-todo-main/web/src/pages/FatalErrorPage/FatalErrorPage'
import FooPageType from '/Users/tobbe/dev/redwood/redwood/__fixtures__/example-todo-main/web/src/pages/FooPage/FooPage'
import HomePageType from '/Users/tobbe/dev/redwood/redwood/__fixtures__/example-todo-main/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/Users/tobbe/dev/redwood/redwood/__fixtures__/example-todo-main/web/src/pages/NotFoundPage/NotFoundPage'
import PrivatePageType from '/Users/tobbe/dev/redwood/redwood/__fixtures__/example-todo-main/web/src/pages/PrivatePage/PrivatePage'
import TypeScriptPageType from '/Users/tobbe/dev/redwood/redwood/__fixtures__/example-todo-main/web/src/pages/TypeScriptPage/TypeScriptPage'
import adminEditUserPageType from '/Users/tobbe/dev/redwood/redwood/__fixtures__/example-todo-main/web/src/pages/admin/EditUserPage/EditUserPage'

declare global {
  const BarPage: typeof BarPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const FooPage: typeof FooPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
  const PrivatePage: typeof PrivatePageType
  const TypeScriptPage: typeof TypeScriptPageType
  const adminEditUserPage: typeof adminEditUserPageType
}
