name: 💬 Message Slack
description: Send a message to slack
inputs:
  title:
    description: title
    required: true
  status:
    description: status
    required: true
  version:
    description: version
    required: true
  slack-webhook-url:
    description: 'Slack webhook URL'
    required: true
runs:
  using: composite
  steps:
    - name: Get emoji
      id: get-emoji
      if: inputs.status == 'failure'
      run: echo "::set-output name=value::🚨"

    - name: Get emoji
      id: get-emoji
      if: inputs.status == 'success'
      run: echo "::set-output name=value::✅"

    - name: 💬 Message Slack
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "title": "${{ inputs.title }}",
            "status": "${{ steps.get-emoji.outputs.value }} ${{ inputs.status == }}",
            "version": "${{ inputs.version }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
