#!/bin/bash

# This publishes a "canary" version of our packages to npm.
# It is run when a branch is merged to main.
# https://github.com/lerna/lerna/tree/master/commands/publish#--canary

yarn lerna publish --canary --force-publish --preid rc --dist-tag rc --yes --loglevel verbose

# --canary
# --preid rc
# --dist-tag rc

# only run when...?
