#!/bin/bash
set -e

# This script republishes our packages to your local npm
# registry (http://localhost:4873).
#
# Usage:
# Publish a single package: ./tasks/local-publish ./packages/api-server
# Publish all the packages: ./tasks/local-publish

if ! lsof -Pi :4873 -sTCP:LISTEN -t >/dev/null; then
  echo "Error: Verdaccio is not listening on port 4873, start it with './tasks/run-local-npm'"
  exit 1
fi


if [ -z "$1" ]
  then
  # Publish all the packages
  for d in packages/*/ ; do
    ( cd "$d" && npm unpublish --tag dev --registry http://localhost:4873/ --force && npm publish --tag dev --registry http://localhost:4873/ --force )
  done
else
  # Publish a single package
  ( cd "$1" && npm unpublish  --tag dev --registry http://localhost:4873/ --force && npm publish --tag dev --registry http://localhost:4873/ --force )
fi
