#!/usr/bin/env node
/* eslint-env node, es6*/

const os = require('os')
const path = require('path')

const execa = require('execa')
const fg = require('fast-glob')
const fs = require('fs-extra')
const yargs = require('yargs')

// This script sets up a blank RedwoodJS app into a directory.
// It uses the packages from the RedwoodJS framework (../packages).
// So, if you're making changes to the framework,
// you can use the e2e tests to verify your changes.
//
// The steps are composable, so that it can work for the GitHub Workflow, and
// us contributors.
//
const makeDirectory = () => {
  console.log('mkdir', REDWOOD_PROJECT_DIRECTORY)
  fs.mkdirSync(REDWOOD_PROJECT_DIRECTORY, { recursive: true })
  return REDWOOD_PROJECT_DIRECTORY
}

const buildRedwoodFramework = () => {
  try {
    const files = fg.sync('packages/**/dist', {
      onlyDirectories: true,
    })

    execa.sync(
      [files.length && 'yarn build:clean', 'yarn build:js']
        .filter(Boolean)
        .join('&&'),
      {
        cwd: REDWOODJS_FRAMEWORK_PATH,
        shell: true,
        stdio: 'inherit',
      }
    )
  } catch (e) {
    console.error('Error: Could not build Redwood Framework')
    console.error(e)
    process.exit(1)
  }
}

const createRedwoodJSApp = () => {
  try {
    execa.sync(
      'yarn babel-node src/create-redwood-app.js',
      [
        REDWOOD_PROJECT_DIRECTORY,
        '--no-yarn-install',
        '--typescript',
        '--no-telemetry',
      ],
      {
        cwd: path.join(REDWOODJS_FRAMEWORK_PATH, 'packages/create-redwood-app'),
        env: { REDWOOD_CI: '1' },
        shell: true,
        stdio: 'inherit',
      }
    )
  } catch (e) {
    console.error('Error: Could not create Redwood Project')
    console.error(e)
    process.exit(1)
  }
}

const addFrameworkDepsToProject = () => {
  try {
    execa.sync('yarn project:deps', {
      cwd: REDWOODJS_FRAMEWORK_PATH,
      shell: true,
      stdio: 'inherit',
      env: {
        RWFW_PATH: REDWOODJS_FRAMEWORK_PATH,
        RWJS_CWD: REDWOOD_PROJECT_DIRECTORY,
      },
    })
  } catch (e) {
    console.error(
      'Error: Could not add Redwood Framework dependencies to project'
    )
    console.error(e)
    process.exit(1)
  }
}

const copyFrameworkPackages = () => {
  try {
    execa.sync('yarn project:copy', {
      cwd: REDWOODJS_FRAMEWORK_PATH,
      shell: true,
      stdio: 'inherit',
      env: {
        RWFW_PATH: REDWOODJS_FRAMEWORK_PATH,
        RWJS_CWD: REDWOOD_PROJECT_DIRECTORY,
      },
    })
  } catch (e) {
    console.error('Error: We could not copy Redwood Framework packages')
    console.error(e)
    process.exit(1)
  }
}
const checkYarnVersion = () => {
  try {
    const { stdout } = execa.sync('yarn --version', {
      cwd: REDWOOD_PROJECT_DIRECTORY,
      shell: true,
    })
    console.log('Yarn version is', stdout)
    if (!stdout.startsWith('1')) {
      setYarnClassic()
    }
  } catch (e) {
    console.error(e)
    console.error('Error: We could not find yarn')
    process.exit(1)
  }
}
const setYarnClassic = () => {
  try {
    execa.sync('yarn set version classic', {
      cwd: REDWOOD_PROJECT_DIRECTORY,
      shell: true,
      stdio: 'inherit',
    })
  } catch (e) {
    console.error(e)
    console.error('Error: We could not set yarn classic')
    process.exit(1)
  }
}
const runYarnInstall = () => {
  try {
    execa.sync('yarn install', {
      cwd: REDWOOD_PROJECT_DIRECTORY,
      shell: true,
      stdio: 'inherit',
    })
  } catch (e) {
    console.error('Error: Could not run `yarn install`')
    console.error(e)
    process.exit(1)
  }
}

const convertProjectToJavaScript = () => {
  try {
    execa.sync('yarn rw ts-to-js', {
      cwd: REDWOOD_PROJECT_DIRECTORY,
      shell: true,
      env: { REDWOOD_CI: '1' },
      stdio: 'inherit',
    })
  } catch (e) {
    console.error('Could not convert the TypeScript app to JavaScript`')
    console.error(e)
    process.exit(1)
  }
}

const runDevServerInBackground = () => {
  console.log('Starting RedwoodJS dev server...')
  execa.sync('yarn rw dev --no-generate --fwd="--no-open" &', {
    cwd: REDWOOD_PROJECT_DIRECTORY,
    shell: true,
    stdio: 'inherit',
    env: {
      RWJS_DELAY_RESTART: '500',
      REDWOOD_CI: '1',
    },
  })
}

const runCypress = () => {
  console.log('Starting Cypress...')
  execa.sync(
    // do not use Yarn to run Cypress; this avoids missing binary errors
    '../../node_modules/.bin/cypress',
    ['open', `--env RW_PATH=${REDWOOD_PROJECT_DIRECTORY}`],
    {
      cwd: path.join(REDWOODJS_FRAMEWORK_PATH, 'tasks/e2e'),
      shell: true,
      stdio: 'inherit',
    }
  )
}

const initGit = () => {
  console.log('Initializing Git')
  execa.sync('git init --initial-branch main && git add .', {
    cwd: REDWOOD_PROJECT_DIRECTORY,
    shell: true,
    stdio: 'inherit',
  })
  execa.sync('git commit -a --message=init', {
    cwd: REDWOOD_PROJECT_DIRECTORY,
    shell: true,
    stdio: 'inherit',
  })
}

const args = yargs
  .option('create-project', { default: true, type: 'boolean', alias: 'create' })
  .option('build-framework', { default: true, type: 'boolean', alias: 'build' })
  .option('copy-framework', { default: true, type: 'boolean', alias: 'copy' })
  .option('typescript', { default: false, type: 'boolean', alias: 'ts' })
  .option('auto-start', { default: true, type: 'boolean', alias: 'start' })
  .scriptName('run-e2e')
  .example('run-e2e')
  .example('run-e2e /tmp/redwood-app --ts')
  .help()
  .strict().argv

const REDWOODJS_FRAMEWORK_PATH = path.resolve(__dirname, '..')
let REDWOOD_PROJECT_DIRECTORY =
  args._?.[0] ||
  path.join(
    os.tmpdir(),
    'redwood-e2e',
    // ":" is problematic with paths
    new Date().toISOString().split(':').join('-')
  )

console.log()
console.log('-'.repeat(80))
console.log()
makeDirectory(REDWOOD_PROJECT_DIRECTORY)
console.log()
console.log('-'.repeat(80))

let { buildFramework, copyFramework, createProject, typescript, autoStart } =
  args
const tasks = [
  buildFramework && buildRedwoodFramework,
  createProject && createRedwoodJSApp,
  copyFramework && addFrameworkDepsToProject,
  copyFramework && checkYarnVersion,
  copyFramework && runYarnInstall,
  copyFramework && copyFrameworkPackages,
  !typescript && convertProjectToJavaScript,
  autoStart && runDevServerInBackground,
  autoStart && initGit,
  autoStart && runCypress,
].filter(Boolean)

for (const task of tasks) {
  console.log()
  task()
  console.log()
  console.log('-'.repeat(80))
}

process.on('SIGINT', () => {
  console.log()
  console.log(REDWOOD_PROJECT_DIRECTORY)
  console.log('-'.repeat(80))
  process.exit(0)
})
