#!/bin/bash
set -e

realpath() {
  path=`eval echo "$1"`
  folder=$(dirname "$path")
  echo $(cd "$folder"; pwd)/$(basename "$path");
}

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

# Install the dependencies required to run the e2e tests.
cd "$SCRIPTPATH/e2e"
yarn install

if [ -z "$1" ]
  then
  echo "You have not supplied a path to a Redwood project."
  echo "We will create one for you."
  echo "We will copy './packages/create-redwood-app/template' and run 'yarn rw upgrade --tag canary'"

  TMP_DIR=$(mktemp -d -t redwood)
  cd ../../packages/create-redwood-app
  yarn babel-node dist/create-redwood-app.js $TMP_DIR

  cd $TMP_DIR
  yarn rw upgrade --tag canary
else
  echo "You have supplied a path $1, we will not create a new "
  echo "Redwood project, we will use the app you have specified."
  TMP_DIR=$1
fi

cd $TMP_DIR

yarn rw dev --fwd="--open=false" & cd "$SCRIPTPATH/e2e"; yarn cypress open --env RW_PATH=$TMP_DIR
