declare module 'react-server-dom-webpack/node-loader'
declare module 'react-server-dom-webpack/server'
declare module 'react-server-dom-webpack/server.node.unbundled'
declare module 'react-server-dom-webpack/client'
declare module 'acorn-loose'
