// This file was generated by RedwoodJS
import { Success } from './TodoListCell'
import type { CellProps } from '@redwoodjs/web'
import type { TodoListCell_GetTodos, TodoListCell_GetTodosVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './TodoListCell'

type CellInputs = CellProps<SuccessType, TodoListCell_GetTodos, TodoListCell_GetTodosVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
