#!/usr/bin/env node
/* eslint-env node, es6*/

const fs = require('fs')
const os = require('os')
const path = require('path')

const tempDirPath = path.join(
  os.tmpdir(),
  `redwood-e2e-${new Date().toISOString().split(':').join('-')}`
)

console.log(fs.mkdtempSync(tempDirPath))
