#!/usr/bin/env node
/* eslint-env node, es6*/
//@ts-check
const fs = require('fs')
const os = require('os')
const path = require('path')

const chalk = require('chalk')
const execa = require('execa')
const fse = require('fs-extra')
const Listr = require('listr2').Listr
const rimraf = require('rimraf')
const { hideBin } = require('yargs/helpers')
const yargs = require('yargs/yargs')

const {
  addFrameworkDepsToProject,
  copyFrameworkPackages,
} = require('./frameworkLinking')
const { webTasks, apiTasks } = require('./tasks')
const {
  getExecaOptions,
  updatePkgJsonScripts,
  confirmNoFixtureNoLink,
} = require('./util')

const args = yargs(hideBin(process.argv))
  .usage('Usage: $0 <project directory> [option]')
  .option('typescript', {
    alias: 'ts',
    default: false,
    type: 'boolean',
    describe: 'Generate a TypeScript project. JavaScript by default.',
  })
  .option('link', {
    default: false,
    type: 'boolean',
    describe:
      'Link the current checked out branch of the framework in the project',
  })
  .option('verbose', {
    default: false,
    type: 'boolean',
    describe: 'Verbose output',
  })
  .option('copyFromFixture', {
    default: true,
    type: 'boolean',
    describe: 'Copy the test project from the __fixtures__ folder',
  })
  .option('rebuildFixture', {
    default: false,
    type: 'boolean',
    describe: 'Rebuild __fixtures__/test-project',
  })
  .option('clean', {
    default: false,
    type: 'boolean',
    describe: 'Delete existing directory, and recreate project',
  })
  .option('canary', {
    default: true,
    type: 'boolean',
    describe:
      'Upgrade project to latest canary version. NOT compatible with --link.',
  })
  .option('yarn1', {
    default: false,
    type: 'boolean',
    describe: 'Use yarn 1 instead of yarn 3',
  })
  .help()
  .parseSync()

const {
  typescript,
  canary,
  link,
  verbose,
  clean,
  copyFromFixture,
  rebuildFixture,
  yarn1,
} = args

// Do not use demandCommand because rebuildFixture doesn't require <project directory>
// Require 1 and only 1 arg if not rebuildFixture
if (!rebuildFixture && args._.length > 1) {
  console.log(
    chalk.default.red.bold(
      `
      Multiple <project directory> arguments
      Specify ONE project directory outside the framework directory (no spaces allowed)
      EXAMPLE: 'yarn build:test-project ../test-project'
      `
    )
  )
  process.exit(1)
} else if (!rebuildFixture && args._.length < 1) {
  console.log(
    chalk.default.red.bold(
      `
      Missing <project directory> argument
      Specify a project directory outside the framework directory
      EXAMPLE: 'yarn build:test-project ../test-project'
      `
    )
  )
  process.exit(1)
}

const OUTPUT_PROJECT_PATH = rebuildFixture
  ? path.join(
      os.tmpdir(),
      'redwood-test-project',
      // ":" is problematic with paths
      new Date().toISOString().split(':').join('-')
    )
  : path.resolve(String(args._))

const RW_FRAMEWORKPATH = path.join(__dirname, '../../')

// Project Directory path check: must not be a subdirectory or Yarn will error
const relativePathCheck = path.relative(RW_FRAMEWORKPATH, OUTPUT_PROJECT_PATH)
if (
  relativePathCheck &&
  !relativePathCheck.startsWith('..') &&
  !path.isAbsolute(relativePathCheck)
) {
  console.log(
    chalk.default.red.bold(
      `
      Project Directory CANNOT be a subdirectory of '${RW_FRAMEWORKPATH}'
      Specify a project directory outside the framework directory
      EXAMPLE: 'yarn build:test-project ../test-project'
      `
    )
  )
  process.exit(1)
}

const createProject = async () => {
  if (clean) {
    rimraf.sync(OUTPUT_PROJECT_PATH)
  }

  let cmd = `yarn babel-node packages/create-redwood-app/src/create-redwood-app.js ${OUTPUT_PROJECT_PATH}`

  // We create a ts project and convert using ts-to-js at the end if typescript flag is false
  return execa(
    cmd,
    ['--no-yarn-install', '--typescript', '--overwrite'],
    getExecaOptions(RW_FRAMEWORKPATH)
  )
}

const copyProject = async () => {
  if (clean && !rebuildFixture) {
    rimraf.sync(OUTPUT_PROJECT_PATH)
  }

  const FIXTURE_TESTPROJ_PATH = path.join(
    RW_FRAMEWORKPATH,
    '__fixtures__/test-project'
  )

  if (rebuildFixture) {
    // remove existing Fixture
    rimraf.sync(FIXTURE_TESTPROJ_PATH)
    // copy from tempDir to Fixture dir
    await fse.copy(OUTPUT_PROJECT_PATH, FIXTURE_TESTPROJ_PATH)
    // cleanup after ourselves
    rimraf.sync(OUTPUT_PROJECT_PATH)
  } else {
    // copying existing Fixture to new Project
    await fse.copy(FIXTURE_TESTPROJ_PATH, OUTPUT_PROJECT_PATH)
    // Make sure no lockfiles are accidentally copied
    fse.remove(path.join(OUTPUT_PROJECT_PATH, 'yarn.lock'))
  }
}

const globalTasks = () =>
  new Listr(
    [
      {
        title: 'Creating project',
        task: (_ctx, task) => {
          if (copyFromFixture && !rebuildFixture) {
            task.output =
              'Copying test-project from __fixtures__/test-project...'
            return copyProject()
          } else {
            task.output = 'Building test-project from scratch...'
            return createProject()
          }
        },
      },
      {
        title: '[link] Building Redwood framework',
        task: async () => {
          try {
            await execa(
              'yarn build:clean && yarn build',
              [],
              getExecaOptions(RW_FRAMEWORKPATH)
            )
          } catch (e) {
            console.log('Failed to build framework...')
            console.log()
            console.log(
              'Please check your branch is building with yarn build:clean && yarn build'
            )
            throw new Error('Failed to build framework')
          }
        },
        enabled: () => link || rebuildFixture,
      },
      {
        title: '[link] Adding framework dependencies to project',
        task: () =>
          addFrameworkDepsToProject(RW_FRAMEWORKPATH, OUTPUT_PROJECT_PATH),
        enabled: () => link || rebuildFixture,
      },
      {
        title: 'Setting yarn version to 1',
        task: async () => {
          await execa(
            'yarn set version classic',
            [],
            getExecaOptions(OUTPUT_PROJECT_PATH)
          )
        },
        enabled: () => yarn1,
      },
      {
        title: 'Installing node_modules',
        task: async () => {
          return execa(
            'yarn install',
            yarn1 &&
              ['--non-interactive', !verbose && '--silent'].filter(Boolean), // pass flags if using Yarn v1
            getExecaOptions(OUTPUT_PROJECT_PATH)
          )
        },
      },
      {
        title: 'Updating ports in redwood.toml...',
        task: () => {
          // We do this, to make it easier to run multiple test projects in parallel
          // But on different ports. If API_DEV_PORT or WEB_DEV_PORT aren't supplied,
          // It just defaults to 8910 and 8911
          // This is helpful in playwright smoke tests to allow us to parallelize
          const REDWOOD_TOML_PATH = path.join(
            OUTPUT_PROJECT_PATH,
            'redwood.toml'
          )
          const redwoodToml = fs.readFileSync(REDWOOD_TOML_PATH).toString()
          let newRedwoodToml = redwoodToml

          newRedwoodToml = newRedwoodToml.replace(
            /\port = 8910/,
            'port = "${WEB_DEV_PORT:8910}"'
          )

          newRedwoodToml = newRedwoodToml.replace(
            /\port = 8911/,
            'port = "${API_DEV_PORT:8911}"'
          )

          fs.writeFileSync(REDWOOD_TOML_PATH, newRedwoodToml)
        },
        enabled: () => rebuildFixture,
      },
      {
        title: '[link] Copying framework packages to project',
        task: () =>
          copyFrameworkPackages(RW_FRAMEWORKPATH, OUTPUT_PROJECT_PATH),
        enabled: () => link || rebuildFixture,
      },
      {
        title: '[link] Add rwfw project:copy postinstall',
        task: () => {
          updatePkgJsonScripts({
            projectPath: OUTPUT_PROJECT_PATH,
            scripts: {
              postinstall: 'yarn rwfw project:copy',
            },
          })
        },
        enabled: () => link || rebuildFixture, // Note that we undo this when we rebuildFixture at the end
      },
      {
        title: 'Upgrading to latest canary version',
        task: async () => {
          return execa(
            'yarn rw upgrade -t canary',
            [],
            getExecaOptions(OUTPUT_PROJECT_PATH)
          )
        },
        enabled: () => canary && !link && !rebuildFixture,
      },
      {
        title: 'Apply web codemods',
        task: () =>
          webTasks(OUTPUT_PROJECT_PATH, {
            verbose,
            linkWithLatestFwBuild: link || rebuildFixture,
          }),
        enabled: () => !copyFromFixture || rebuildFixture,
      },
      {
        title: 'Apply api codemods',
        task: () =>
          apiTasks(OUTPUT_PROJECT_PATH, {
            verbose,
            linkWithLatestFwBuild: link || rebuildFixture,
          }),
        enabled: () => !copyFromFixture || rebuildFixture,
      },
      {
        title: 'Generate dbAuth Secret',
        task: async () => {
          const { stdout: dbAuthSecret } = await execa(
            'yarn',
            [yarn1 && '--silent', 'rw', 'g', 'secret', '--raw'].filter(Boolean),
            {
              ...getExecaOptions(OUTPUT_PROJECT_PATH),
              stdio: 'pipe',
            }
          )

          fs.appendFileSync(
            path.join(OUTPUT_PROJECT_PATH, '.env'),
            `SESSION_SECRET=${dbAuthSecret}`
          )
        },
        enabled: () => !rebuildFixture,
      },
      {
        title: 'Running prisma migrate reset',
        task: () => {
          return execa(
            'yarn rw prisma migrate reset',
            ['--force'],
            getExecaOptions(OUTPUT_PROJECT_PATH)
          )
        },
      },
      {
        title: 'Convert to JS',
        task: async (_ctx, task) => {
          if (!rebuildFixture) {
            return execa(
              'yarn rw ts-to-js',
              [],
              getExecaOptions(OUTPUT_PROJECT_PATH)
            )
          } else {
            task.output = 'Rebuilding Fixture: skip ts-to-js'
          }
        },
        enabled: () => !typescript,
      },
      {
        title: 'Lint --fix all the things',
        task: async () => {
          try {
            await execa('yarn rw lint --fix', [], {
              shell: true,
              stdio: 'ignore',
              cleanup: true,
              cwd: OUTPUT_PROJECT_PATH,
              env: {
                RW_PATH: path.join(__dirname, '../../'),
              },
            })
          } catch (e) {
            // nothing to see here
          }
        },
        enabled: () => rebuildFixture || !copyFromFixture,
      },
      {
        title: '[Rebuild Fixture] Replace and Cleanup Fixture',
        task: async () => {
          // @TODO: This only works on UNIX, we should use path.join everywhere
          // remove all .gitignore
          rimraf.sync(`${OUTPUT_PROJECT_PATH}/.redwood`)
          rimraf.sync(`${OUTPUT_PROJECT_PATH}/api/db/dev.db`)
          rimraf.sync(`${OUTPUT_PROJECT_PATH}/api/db/dev.db-journal`)
          rimraf.sync(`${OUTPUT_PROJECT_PATH}/api/dist`)
          rimraf.sync(`${OUTPUT_PROJECT_PATH}/node_modules`)
          rimraf.sync(`${OUTPUT_PROJECT_PATH}/web/node_modules`)
          rimraf.sync(`${OUTPUT_PROJECT_PATH}/.env`)
          rimraf.sync(`${OUTPUT_PROJECT_PATH}/yarn.lock`)

          // Copy over package.json from template, so we remove the extra dev dependencies, and rwfw postinstall script
          // that we added in "Adding framework dependencies to project"
          rimraf.sync(`${OUTPUT_PROJECT_PATH}/package.json`)
          fs.copyFileSync(
            path.join(
              __dirname,
              '../../packages/create-redwood-app/template/package.json'
            ),
            path.join(OUTPUT_PROJECT_PATH, 'package.json')
          )

          // removes existing Fixture and replaces with newly built project,
          // then removes new Project temp directory
          copyProject()
        },
        enabled: () => rebuildFixture,
      },
      {
        title: 'All done!',
        task: async (_ctx, task) => {
          if (verbose) {
            // Without verbose these logs aren't visible anyway
            console.log()
            console.log('-'.repeat(30))
            console.log()
            console.log('✅ Success your project has been generated at:')
            console.log(OUTPUT_PROJECT_PATH)
            console.log()
            console.log('-'.repeat(30))
          } else {
            task.output = `Generated project at ${OUTPUT_PROJECT_PATH}`
          }
        },
      },
    ],
    {
      exitOnError: true,
      renderer: verbose && 'verbose',
      renderOptions: { collapse: false },
    }
  )

async function runCommand() {
  // confirm usage for case raw build without Link
  if (!copyFromFixture && !link) {
    // if prompt returns 'no', exit
    ;(await confirmNoFixtureNoLink(copyFromFixture, link)) || process.exit(1)
  }

  await globalTasks()
    .run()
    .catch((err) => {
      console.error(err)
      process.exit(1)
    })
}

runCommand()
