// This file was generated by RedwoodJS
import { Success } from './NumTodosTwoCell'
import type { CellProps } from '@redwoodjs/web'
import type { NumTodosCell_GetCount, NumTodosCell_GetCountVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './NumTodosTwoCell'

type CellInputs = CellProps<SuccessType, NumTodosCell_GetCount, NumTodosCell_GetCountVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
