import fs from 'fs'
import path from 'path'

import { transformWithEsbuild } from 'vite'
import type { PluginOption } from 'vite'

import { getPaths } from '@redwoodjs/project-config'

const DEFAULT_POSSIBLE_TYPES_FILE_CONTENTS =
  'export default { possibleTypes: {} }'
// TODO: Change the name to virtual:possibleTypes when we no longer have to
// support Webpack
const virtualPossibleTypesModuleId = 'virtual-possibleTypes'
const virtualPossibleTypesResolvedId = '\0' + virtualPossibleTypesModuleId

/**
 * This is a vite plugin to support GraphQL Fragments by either returning empty
 * default possibleTypes to be used when setting the Apollo Client Cache config
 * or allowing Apollo Client to use the possibleTypes file that is generated by
 * the GraphQL Code Generator
 *
 * See:
 * packages/web/src/apollo/index.ts -> import possibleTypes from 'virtual-possibleTypes'
 */
export default function configureGraphQLFragments(): PluginOption {
  const possibleTypesFilePath = path.join(
    getPaths().web.graphql,
    'possibleTypes.ts'
  )

  const existsPossibleTypesFile = fs.existsSync(possibleTypesFilePath)

  return {
    name: 'configure-graphql-fragments',
    resolveId(id) {
      if (id === virtualPossibleTypesModuleId) {
        return virtualPossibleTypesResolvedId
      }

      return null
    },
    async load(id: string) {
      if (id === virtualPossibleTypesResolvedId) {
        if (existsPossibleTypesFile) {
          const possibleTypeFile = fs.readFileSync(
            possibleTypesFilePath,
            'utf8'
          )

          const result = await transformWithEsbuild(
            possibleTypeFile,
            possibleTypesFilePath,
            {
              loader: 'ts',
            }
          )

          return result.code
        } else {
          return DEFAULT_POSSIBLE_TYPES_FILE_CONTENTS
        }
      }

      return null
    },
  }
}
