// Could also have used `import 'server-only'
import '@jtoar/throw-on-client'

const RANDOM_WORDS = [
  'unicorns',
  'roses',
  'butterflies',
  'stocks',
  'pommie',
  'rollers',
  'wennier',
  'demandingly',
  'desiccation',
  'terranes',
  'emblazonries',
  'gashest',
  'discordant',
  'swanskins',
  'interpersonally',
  'limites',
  'maternal',
  'pit',
  'pseudocoels',
  'keratoses',
  'neptunium',
  'scavenger',
  'pronunciational',
  'judicially',
  'swordsmanships',
  'scootches',
  'detonability',
  'brockage',
  'aversenesses',
  'merchantmen',
  'revengefully',
  'enteropathy',
  'aventail',
  'vodun',
  'flies',
  'promotable',
  'noncallable',
  'sociograms',
  'inseams',
  'ankylotic',
  'dronish',
  'interpolated',
  'caroli',
  'brocoli',
  'nattier',
  'dysphonic',
  'antiqued',
  'arachnid',
  'jibed',
  'dogmatizer',
  'inerrant',
  'reecho',
  'clime',
  'thousandth',
  'wheedled',
  'interpolate',
  'schizogonies',
  'occupancies',
  'lousy',
  'publicnesses',
  'dogging',
  'kithing',
  'mikrons',
  'pongee',
  'cataphora',
  'elvishly',
  'interpsychic',
  'nebulizations',
  'unguinous',
  'crackups',
  'viewier',
  'wideouts',
  'lintwhites',
  'gravelling',
  'spermophiles',
  'plasminogens',
  'operation',
  'eye',
  'tenpence',
  'prized',
  'parenthoods',
  'nerd',
  'belted',
  'herringbones',
  'infatuates',
  'ectypes',
  'subadolescent',
  'waggoning',
  'isospins',
  'carbonless',
  'tremolitic',
  'interglacial',
  'overstir',
  'rescued',
  'viridity',
  'deputation',
  'alkane',
  'laminas',
  'switchyards',
  'misagents',
]

export async function randomWords(count: number) {
  // Simulate a network request (50 - 100 ms delay)
  await new Promise((resolve) => setTimeout(resolve, 50 + Math.random() * 50))

  return new Array(count)
    .fill(null)
    .map(() => RANDOM_WORDS[Math.floor(Math.random() * RANDOM_WORDS.length)])
}
